version: '3'
services:

  db:
    container_name: school_db
    image: mariadb:10.6
    volumes:
      - ./.data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_DATABASE: drupal

  drupal:
    container_name: school_drupal
    image: reg.hcpss.org/schools/drupal
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./docker/drupal/Dockerfile
    volumes:
      - ./drupal:/var/www/drupal
      - ./docker/drupal/php.ini-development:/usr/local/etc/php/php.ini
      - ./schools/bbes/config/hcpss_school.settings.yml:/var/www/drupal/config/sync/hcpss_school.settings.yml
      - ./schools/bbes/content:/var/www/drupal/content/snapshot
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_DATABASE: drupal

  web:
    container_name: school_web
    image: nginx:latest
    volumes:
      - ./drupal:/var/www/drupal
      - ./site.conf:/etc/nginx/conf.d/default.conf:ro
      - ./server.conf:/etc/nginx/nginx.conf:ro
      # - ~/.aws:/root/.aws
      # - ./extensions:/extensions
    ports:
      - 8040:80
    depends_on:
      - drupal
    environment:
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
