<?php

use Drupal\fragments\Entity\Fragment;
use Drupal\entityqueue\Entity\EntityQueue;

/**
 * Implementation of hook_contextual_links_alter().
 */
function hcpss_school_contextual_links_alter(array &$links, $group, array $route_parameters) {  
  switch ($group) {
    case 'fragment':
      $fragment = Fragment::load($route_parameters['fragment']);
      
      if ($fragment) {
        foreach ($links as &$link) {
          $link['title'] = str_replace('fragment', $fragment->bundle(), $link['title']);
        }
      }
      
      break;
    case 'entityqueue':
      $queue = EntityQueue::load($route_parameters['entity_subqueue']);
      
      if ($queue) {
        foreach ($links as &$link) {
          $link['title'] = str_replace('subqueue', $queue->label(), $link['title']);
        }
      }
      
      break;
  }
}

/**
 * Implementation of hook_preprocess_HOOK.
 */
function hcpss_school_preprocess_fragment(&$variables) {
  $item = &$variables['content']['title'][0];
  $fragment = $variables['content']['#fragment'];
  
  $item['#template'] = '<a href="{{ url }}">{{ value }}</a>';
  $item['#context']['url'] = $fragment->field_link->uri;
}
